//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoveryHuntApi.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiscoveryHunt_DBEntities : DbContext
    {
        public DiscoveryHunt_DBEntities()
            : base("name=DiscoveryHunt_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Trial> Trials { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersResult> UsersResults { get; set; }
        public virtual DbSet<UserTrialStatu> UserTrialStatus { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
    }
}
