//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoveryHuntApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersResult
    {
        public int ResultId { get; set; }
        public Nullable<int> QuestionAttempt { get; set; }
        public int QuestionId { get; set; }
        public int UserId { get; set; }
        public int TrialId { get; set; }
        public Nullable<int> AnswerStatus { get; set; }
    
        public virtual Trial Trial { get; set; }
        public virtual Trial Trial1 { get; set; }
        public virtual User User { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual Question Question { get; set; }
    }
}
