//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoveryHuntApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTrialStatu
    {
        public int UserTrialStatusId { get; set; }
        public int TrialId { get; set; }
        public int UserId { get; set; }
        public Nullable<decimal> ProgressLevel { get; set; }
        public Nullable<decimal> WaterLevel { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<System.TimeSpan> PauseTime { get; set; }
        public Nullable<System.TimeSpan> Penalty { get; set; }
    
        public virtual Trial Trial { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
